apiVersion: v1
kind: Pod
metadata:
  name: busybox-nas
spec:
  containers:
  - args:
    - /bin/sh
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: nginx-php
  restartPolicy: Never
